---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vyogo-tech-v1alpha1-frappebench
  failurePolicy: Fail
  name: vfrappebench.kb.io
  rules:
  - apiGroups:
    - vyogo.tech
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frappebenches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vyogo-tech-v1alpha1-frappesite
  failurePolicy: Fail
  name: vfrappesite.kb.io
  rules:
  - apiGroups:
    - vyogo.tech
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frappesites
  sideEffects: None
