apiVersion: vyogo.tech/v1alpha1
kind: FrappeSite
metadata:
  name: demo-site
  namespace: frappe-demo
spec:
  benchRef:
    name: demo-bench
    namespace: frappe-demo
  
  # Site domain
  siteName: demo-site.example.com
  
  # Database configuration (Shared Instance from frappe-operator-system)
  dbConfig:
    provider: mariadb
    mode: shared
    mariadbRef:
      name: frappe-mariadb
      namespace: frappe-operator-system
  
  # Ingress configuration for OpenShift (Enabled to trigger Route)
  ingress:
    enabled: true
    className: openshift-default
