apiVersion: vyogo.tech/v1alpha1
kind: FrappeBench
metadata:
  name: fixes-bench
  namespace: frappe-fixes
spec:
  frappeVersion: "15.0.0"
  imageConfig:
    repository: ghcr.io/rmallam/frappe_docker
    tag: sha-c39d75f
    pullPolicy: Always
  storageClassName: ocs-external-storagecluster-cephfs
  storageSize: 2Gi

 # Apps to install
  apps:
    - name: frappe
      source: image
    - name: erpnext
      source: image

  # Component replicas (minimal for development)
  componentReplicas:
    gunicorn: 1
    nginx: 1
    socketio: 1
    scheduler: 1
    workers:
      default: 1
      short: 0
      long: 0