apiVersion: vyogo.tech/v1alpha1
kind: FrappeSite
metadata:
  name: vyogotech
  namespace: frappe
spec:
  siteName: vyogo.apps-crc.testing
  benchRef:
    name: bench-test
    namespace: frappe

  # Database configuration
  dbConfig:
    provider: mariadb
    mode: shared
    mariadbRef:
      name: frappe-mariadb
      namespace: mariadb

  # Ingress configuration for OpenShift
  ingress:
    enabled: true
    className: openshift-default
  

