apiVersion: vyogo.tech/v1alpha1
kind: FrappeSite
metadata:
  name: new-site2
  namespace: frappe-fixes
spec:
  siteName: new-site2.apps.cluster-5x9wt.dynamic.redhatworkshops.io
  benchRef:
    name: new-bench
    namespace: frappe-fixes

  # Database configuration
  dbConfig:
    provider: mariadb
    mode: shared
    mariadbRef:
      name: frappe-mariadb
      namespace: frappe-operator-system

  # Ingress configuration for OpenShift
  ingress:
    enabled: true
    className: openshift-default
  

