apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: frappe-mariadb
  namespace: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root-password
    key: password
  image: mariadb:10.11
  storage:
    size: 2Gi
  replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-root-password
  namespace: mariadb
type: Opaque
stringData:
  password: frappe
---
apiVersion: v1
kind: Secret
metadata:
  name: e2e-admin-password
  namespace: default
type: Opaque
stringData:
  password: admin